name: gr310
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - adwaita-icon-theme=41.0=ha770c72_1
  - alsa-lib=1.2.6.1=h7f98852_0
  - alsa-plugins=1.2.6=h5c30c6c_0
  - aom=3.4.0=h27087fc_1
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.36.0=h3371d22_4
  - attr=2.5.1=h166bdaf_0
  - attrs=22.1.0=pyh71513ae_1
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_10
  - boost-cpp=1.74.0=h75c5d50_8
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py310h5764c6d_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.6.15=ha878542_0
  - cairo=1.16.0=ha61ee94_1011
  - certifi=2022.6.15=py310hff52083_0
  - cffi=1.15.1=py310h255011f_0
  - charset-normalizer=2.1.0=pyhd8ed1ab_0
  - clang-format=14.0.6=default_h2e3cab8_0
  - clang-format-14=14.0.6=default_h2e3cab8_0
  - click=8.1.3=py310hff52083_0
  - click-plugins=1.1.1=py_0
  - cmake=3.23.3=h5432695_0
  - cryptography=37.0.4=py310h597c629_0
  - cxx-compiler=1.0.0=hf484d3e_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - epoxy=1.5.10=h166bdaf_1
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.4.2=gpl_h2b602b6_106
  - fftw=3.3.10=nompi_h77c792f_102
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.34.4=py310h5764c6d_0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - gcc=10.4.0=hb92f740_10
  - gcc_impl_linux-64=10.4.0=h7ee1905_16
  - gcc_linux-64=10.4.0=h9215b83_10
  - gdk-pixbuf=2.42.8=hff1cb4f_0
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.72.1=h6239696_0
  - glib-tools=2.72.1=h6239696_0
  - gmp=6.2.1=h58526e2_0
  - gnuradio=3.10.3.0=py310hb890b00_2
  - gnuradio-core=3.10.3.0=py310h179aa5a_2
  - gnuradio-grc=3.10.3.0=py310h0dc8b28_2
  - gnuradio-iio=3.10.3.0=py310h3058d4e_2
  - gnuradio-qtgui=3.10.3.0=py310hc030b51_2
  - gnuradio-soapy=3.10.3.0=py310h00a44fc_2
  - gnuradio-uhd=3.10.3.0=py310he2bccb3_2
  - gnuradio-video-sdl=3.10.3.0=py310h0dc8b28_2
  - gnuradio-zeromq=3.10.3.0=py310h935459f_2
  - gnutls=3.7.6=hf3e180e_5
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.7=he838d99_0
  - gst-plugins-base=1.20.3=hf6a322e_0
  - gstreamer=1.20.3=hd4edc92_0
  - gstreamer-orc=0.4.32=h7f98852_1
  - gtk3=3.24.34=h4d20fae_1
  - gxx_impl_linux-64=10.4.0=h7ee1905_16
  - gxx_linux-64=10.4.0=h6e491c6_10
  - harfbuzz=5.1.0=hf9f4e7c_0
  - hicolor-icon-theme=0.17=ha770c72_2
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py310hff52083_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - jack=1.9.18=h8c3723f_1002
  - jpeg=9e=h166bdaf_2
  - jsonschema=4.9.0=pyhd8ed1ab_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libad9361-iio=0.2=hebf0105_3
  - libaio=0.3.113=h166bdaf_0
  - libblas=3.9.0=15_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcap=2.64=ha37c62d_0
  - libcblas=3.9.0=15_linux64_openblas
  - libclang=14.0.6=default_h2e3cab8_0
  - libclang-cpp14=14.0.6=default_h2e3cab8_0
  - libclang13=14.0.6=default_h3a83d3e_0
  - libcodec2=1.0.3=h7f98852_0
  - libcups=2.3.3=hf5a7f15_1
  - libcurl=7.83.1=h7bff187_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.12=h166bdaf_0
  - libdrm=2.4.112=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.4=h27087fc_0
  - libgcc-devel_linux-64=10.4.0=h74af60c_16
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgirepository=1.72.0=h26ff761_1
  - libglib=2.72.1=h2d90d5f_0
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.3=h166bdaf_0
  - libiio-c=0.24=hb303f27_0
  - liblapack=3.9.0=15_linux64_openblas
  - libllvm14=14.0.6=he0ac6c6_0
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.20=pthreads_h78a6416_1
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h753d276_3
  - libpq=14.4=hd77ab85_0
  - librsvg=2.54.4=h7abd40a_0
  - libsanitizer=10.4.0=hde28e3b_16
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-devel_linux-64=10.4.0=h74af60c_16
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.18.0=h166bdaf_1
  - libthrift=0.16.0=h519c5ea_1
  - libtiff=4.4.0=h0d92c0b_2
  - libtool=2.4.6=h9c3ff4c_1008
  - libudev1=249=h166bdaf_4
  - libunistring=0.9.10=h7f98852_0
  - libusb=1.0.26=h0b4f0b6_100
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.44.2=h166bdaf_0
  - libva=2.15.0=h166bdaf_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.3=h522a892_1
  - libwebp-base=1.2.3=h166bdaf_2
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h22db469_3
  - libxslt=1.1.35=h8affb1d_0
  - libzlib=1.2.12=h166bdaf_2
  - lxml=4.9.1=py310h5764c6d_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mako=1.2.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h5764c6d_1
  - matplotlib-base=3.5.2=py310h5701ce4_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.29=haf5c9bc_1
  - mysql-libs=8.0.29=h28c427c_1
  - ncurses=6.3=h27087fc_1
  - nettle=3.8.1=hc379101_1
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numpy=1.23.1=py310h53a5b5f_0
  - openh264=2.2.0=h27087fc_2
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1q=h166bdaf_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=21.3=pyhd8ed1ab_0
  - pango=1.50.8=hc4f8a73_1
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.2.0=py310he619898_0
  - pip=22.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - ply=3.11=py_1
  - portaudio=19.6.0=h57a0ea0_5
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio=14.0=h7f54b18_8
  - pybind11=2.10.0=py310hbf28c38_0
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.10.0=py310hbf28c38_0
  - pycairo=1.21.0=py310h96fc21a_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pygobject=3.42.2=py310h964465f_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py310h29803b5_0
  - pyqt5-sip=12.11.0=py310hd8f1fbe_0
  - pyqtgraph=0.12.4=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py310h5764c6d_1
  - pysocks=1.7.1=py310hff52083_5
  - python=3.10.5=h582c2e5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pyyaml=6.0=py310h5764c6d_4
  - pyzmq=23.2.0=py310h330234f_0
  - qt-main=5.15.4=ha5833f6_2
  - qwt=6.2.0=h1d9fb53_4
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_0
  - rhash=1.4.3=h166bdaf_0
  - ruamel.yaml=0.17.21=py310h5764c6d_1
  - ruamel.yaml.clib=0.2.6=py310h5764c6d_1
  - scipy=1.9.0=py310hdfbd76f_0
  - sdl=1.2.52=h27087fc_1
  - sdl2=2.0.22=h55ee7ae_2
  - setuptools=63.3.0=py310hff52083_0
  - sip=6.6.2=py310hd8f1fbe_0
  - six=1.16.0=pyh6c4a22f_0
  - soapysdr=0.8.1=py310hbf28c38_2
  - spdlog=1.10.0=h924138e_0
  - sqlite=3.39.2=h4ff8645_0
  - svt-av1=1.1.0=h27087fc_1
  - sysroot_linux-64=2.12=he073ed8_15
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tzdata=2022a=h191b570_0
  - uhd=4.2.0.1=py310h8c4ac1a_0
  - unicodedata2=14.0.0=py310h5764c6d_1
  - urllib3=1.26.11=pyhd8ed1ab_0
  - volk=2.5.1=h9c3ff4c_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h8a70e8d_2
  - pip:
    - castxml==0.4.3
    - pygccxml==2.2.1

